main: com.coloredcarrot.rightclickitempickup.RCIPPlugin
name: RightClickItemPickup
version: 1.3.1
author: ColoredCarrot

commands:
  rcip:
    usage: "§cUsage: /rcip <enable,disable,toggle>"
    aliases: [rightclickitempickup]
    permission-message: "§4Insufficient permissions"

permissions:
  rcip:
    default: op
    children:
      rcip.enable: true
      rcip.disable: true
  
  rcip.enable:
    default: op
  
  rcip.disable:
    default: op  
  